default: &default
  adapter: postgresql
  timeout: 5000
  encoding: unicode
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: lof_test

development:
  <<: *default
  database: lof_development
