default: &default
  adapter: postgresql
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  username: libros
  timeout: 5000
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: lof_test

development:
  <<: *default
  database: lof_development
