default: &default
  adapter: postgresql
  host: localhost
  port: 6666
  timeout: 5000
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: lof_test
  username: lof
  password: lof

development:
  <<: *default
  database: lof_development
  username: lof
  password: lof
